GPUS: 0
Rot_type: 6D
backbone: hrnet
batch_size: 64
beta_dim: 10
calc_PVE_error: false
cam_dim: 3
centermap_conf_thresh: 0.25
centermap_size: 64
collision_aware_centermap: false
collision_factor: 0.2
configs_yml: /dartfs/rc/lab/S/Scraplab/packages/ROMP/src/ROMP_psypose/configs/video.yml
dataset_rootdir: /dartfs/rc/lab/S/Scraplab/packages/dataset/
deconv_num: 0
demo_image_folder: None
eval: false
fine_tune: true
fps_save: 30
gmodel_path: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/trained_models/ROMP_hrnet32.pkl
gpu: '0'
high_resolution: true
input_size: 512
kernel_sizes:
- 5
kp3d_format: smpl24
local_rank: 0
log_path: /dartfs/rc/lab/S/Scraplab/packages/log/
max_person: 64
model_precision: fp32
model_version: 1
multi_person: true
multiprocess: false
nw: 4
print_freq: 50
rot_dim: 6
save_best_folder: /dartfs/rc/lab/S/Scraplab/packages/checkpoints/
save_centermap: false
save_dict_results: false
save_mesh: false
save_video_results: false
smpl_J_reg_extra_path: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/smpl/J_regressor_extra.npy
smpl_J_reg_h37m_path: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/smpl/J_regressor_h36m.npy
smpl_female_texture: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/smpl/SMPL_sampleTex_f.jpg
smpl_joint_num: 22
smpl_male_texture: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/smpl/SMPL_sampleTex_m.jpg
smpl_mean_param_path: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/satistic_data/neutral_smpl_mean_params.h5
smpl_model: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/statistic_data/neutral_smpl_with_cocoplus_reg.txt
smpl_model_path: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data
smpl_uvmap: /dartfs-hpc/rc/home/n/f004swn/.ROMP/ROMP_data/smpl/uv_table.npy
smplx_model: true
tab: hrnet_cm64_test
total_param_count: 85
use_coordmaps: true
val_batch_size: 1
video_or_frame: true
webcam: false
webcam_mesh_color: ghostwhite
